### ISSUE TITLE
Link broken on the docs

### ISSUE THREAD

**Issue by marimeireles** [jupyter-xeus/xeus#211]
On [this](https://xeus.readthedocs.io/en/latest/usage.html) page. The [example](https://github.com/jupyter-xeus/xeus/blob/master/docs/source/example) link links to a 404.

Should it maybe link to xeus-calc?
(I can fix it, just tell me where to link or if I should remove it =) )

**Comment by SylvainCorlay** [comment]
Thanks, that is a good idea.

The original example kernel is available in the tests of xeus.

**Comment by JohanMabille** [comment]
Good catch! It should point to https://github.com/jupyter-xeus/xeus/tree/master/example

**Comment by JohanMabille** [comment]
Also adding `xeus-calc` in the lists of available kernels based on xeus could be a good idea. Or in a dedicated sentence something like "a more advanced example kernel can be found here (with link to xeus-calc)".

**Comment by marimeireles** [comment]
Alright. Can do that. :)
