### ISSUE TITLE
No throw when json dump

### ISSUE THREAD

**Issue by wangfenjin** [jupyter-xeus/xeus#242]
nljson would throw if there is invalid utf-8 encoding, would we set to replace or ignore?

https://github.com/nlohmann/json/issues/1198

**Comment by wangfenjin** [comment]
Hi team, do we have any update on this issue? If you have other suggestions maybe I can help to contribute the code.

I'm development a ClickHouse kernel https://github.com/wangfenjin/xeus-clickhouse using xeus, xeus will throw if there a invalid encoding string in the DB.

**Comment by JohanMabille** [comment]
Hi, I don't think we want to force handling invalid utf-8 encoding with replace or ignore for all the kernels based on xeus. Passing an option to the kernel constructor (or server constructor) seems a more appropriate approach, what do you think?

**Comment by wangfenjin** [comment]
Yeah that will be great! Thanks!
