### ISSUE TITLE
[API] Provide replies builders

### ISSUE THREAD

**Issue by JohanMabille** [jupyter-xeus/xeus#274]
As suggested in https://github.com/jupyter/nbclient/pull/142, it would make sense for xeus to provide methods that build the json replies. This would avoid the need to check the protocol for kernel authors.

**Comment by SylvainCorlay** [comment]
@marimeireles

**Comment by JohanMabille** [comment]
These methods have been added in https://github.com/jupyter-xeus/xeus/blob/main/include/xeus/xhelper.hpp
