### ISSUE TITLE
Mamba's libuuid interferes with systems and throws warning

### ISSUE THREAD

**Issue by marimeireles** [jupyter-xeus/xeus#284]
The readme is saying for Linux users to install:

```
mamba install libuuid -c conda-forge
```

But for me that actually breaks the building process. I'm on an Ubuntu 20.04 and it conflicts with the local libuuid.

```
CMake Warning at CMakeLists.txt:224 (add_library):
  Cannot generate a safe runtime search path for target xeus because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libuuid.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/mariana/miniconda3/envs/xeus/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:341 (xeus_create_target)
```

If I uninstall it and trust the system's works well. I don't know if we should add this to the readme or if it's just my awkward linux.

**Comment by SylvainCorlay** [comment]
Is this preventing xeus from building correctly?

**Comment by JohanMabille** [comment]
@marimeireles Do you use CMake from your system? If so, cna you try with installing cmake from conda, and build with it?

**Comment by marimeireles** [comment]
>Is this preventing xeus from building correctly?

Ah! You're right, it doesn't crash my build :see_no_evil: I just get spooked when I see msgs on my CMAKE output.
It seems like it's working fine, even though, it's not listed on my `mamba list`, is that bc it's a c++ thing and mamba doesn't capture it smh? (sorry for the delay I missed the ping).

> @marimeireles Do you use CMake from your system? If so, can you try with installing cmake from conda, and build with it?

Just tried with conda's cmake, same result.

**Comment by martinRenou** [comment]
I've seen similar warnings while always using conda-forge's cmake. Not sure what is causing this. But it doesn't prevent it to work.

**Comment by JohanMabille** [comment]
I think it should disappear if you use a whole build tool chain from conda-forge: cmake, compilers and binutils.
But anyway, it does not prevent the build to cmoplete (and the resulting binary works like a charm).

**Comment by marimeireles** [comment]
> if you use the whole build tool chain from conda-forge: cmake, compilers and binutils.

Didn't work for me. But

> But anyway, it does not prevent the build to cmoplete (and the resulting binary works like a charm).

yeah, exactly :)

**Comment by SylvainCorlay** [comment]
Closing as answered.
