### ISSUE TITLE
RTTI is required

### ISSUE THREAD

**Issue by wolfv** [jupyter-xeus/xeus#331]
I was upgrading LFortran to use the latest `xeus`. LFortran (by default) adds a `-fno-rtti` flag. This crashes in the `dynamic_cast<xcontext_impl<T>*>(this);`.

Would a `static_cast<...>` instead work?

**Comment by wolfv** [comment]
I can confirm that a `static_cast<...>` works. I guess we loose the type check.

**Comment by JohanMabille** [comment]
This (the dynamic_cast) is something we want to keep, especially now that the instantiation of the context is done in external libraries. It has been replaced with a static_cast for now, because of hidden symbols issues, but it should be restored in the next major release.
