### ISSUE TITLE
Provide a main helper function

### ISSUE THREAD

**Issue by AntoinePrv** [jupyter-xeus/xeus#335]
The main function provided in the cookie cutter has some ~150L

https://github.com/jupyter-xeus/xeus-cookiecutter/blob/main/%7B%7Bcookiecutter.github_project_name%7D%7D/src/main.cpp

As with all things cookie-cutter, it is difficult to maintain for Xeus developers and to update for kernel developers.
We should provide it as an helper function.

**Comment by JohanMabille** [comment]
This [file](https://github.com/jupyter-xeus/xeus/blob/main/include/xeus/xhelper.hpp) contains functions that factorize parts of the `main` function of other kernels. We could add those missing.

**Comment by AntoinePrv** [comment]
Thanks, this solved most of it.
