### ISSUE TITLE
Misleading name print_starting_message

### ISSUE THREAD

**Issue by AntoinePrv** [jupyter-xeus/xeus#342]
`print_starting_message` does not print but returns a string.

https://github.com/jupyter-xeus/xeus/blob/3ec5cecae0c17466fbb7196a7fab8f1e471dee7a/src/xhelper.cpp#L12

**Comment by JohanMabille** [comment]
https://github.com/jupyter-xeus/xeus/pull/363 introduces a new `get_starting_message` and deprecates `print_starting_message`

**Comment by IsabelParedes** [comment]
#363 introduced `get_starting_message` and `get_started_message`. The second one is possibly a typo, but which one is preferred?

Or would it be better to have something like `get_start_message` in v4.0 to avoid confusion?

**Comment by JohanMabille** [comment]
@IsabelParedes sorry I missed your comment, `get_started_message` is indeed a typo. Both other options are fine with me, I let you pick up one ;)
