### ISSUE TITLE
Error in install: mamba: error: unrecognized arguments: -c conda-forge

### ISSUE THREAD

**Issue by richelbilderbeek** [jupyter-xeus/xeus#378]
Dear xeus devs,

Xeus seems great, so I followed the instructions to install it:

```
$ mamba install xeus -c conda-forge                                  
usage: mamba [-h] [--version] [--slow SLOW] [--enable-coverage]                            
             [--coverage-file COVERAGE_FILE] [--format FORMAT] [--no-color] [--tags TAGS]  
             [specs ...]                                                                   
mamba: error: unrecognized arguments: -c conda-forge                                       
```

I check the version of `mamba`:

```
$ mamba --version                                                    
0.11.3                                                                                     
```

How do I install xeus? I hope the install instructions will be changed, so that future people like me can also get this running :-) !

**Comment by martinRenou** [comment]
Thanks for opening an issue!

It seems you've installed mamba with pip, which is not the right mamba! The mamba package on PyPi is a utility for running tests https://pypi.org/project/mamba.

The mamba you would need is the one from https://github.com/mamba-org/mamba.

Alternatively you can also use conda if you prefer.
