### ISSUE TITLE
ABI break with minor version bump in nlohmann::json

### ISSUE THREAD

**Issue by chronitis** [jupyter-xeus/xeus#381]
The public API for libxeus includes references to `nlohmann::json` (for instance, https://github.com/jupyter-xeus/xeus/blob/ebd21e9e7cfe143b4d0a6783112cc9006b456915/include/xeus/xdebugger.hpp#L55-L60)

This means that the effective ABI of libxeus is tied to the exact expansion of that template. We encountered this trying to compile a kernel when the local version of `nlohmann::json` was 3.11.3 against a copy of libxeus which had been compiled earlier using `nlohmann::json` 3.11.2.

Attempting to compile xeus-python in these circumstances generates a lot of errors like:

```
main.cpp:(.text+0x58b): undefined reference to `xeus::make_null_debugger(xeus::xcontext&, xeus::xconfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&)'
```

since the expansion of `nlohmann::json` (and hence, the libxeus ABI) has changed from

```
nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned
long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >
```

to

```
nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned
long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>
```

(extra `, void>` at the end of the template)

I don't have a particularly good idea for how to prevent this short of changing the uses of `nlohmann::json` in the API to serialised JSON strings, which probably adds quite a bit of overhead (in addition to being a breaking change in it's own right).

Reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1060164 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061007

I've not seen this issue before, so it may be that ABI breaks from nlohmann::json are quite rare.

**Comment by JohanMabille** [comment]
Hi,

Thanks for reporting! Indeed ABI breaks from nlohmann::json are quite rare, and usually on minor updates, not patch updates.
I guess we should explicitely specify the abi namespace in the API instead of relying on the default value. I haven't checked the detail, so I don't know if nlohmann maintains an explicit backward ABI compatibility, or if that would lead to a compilation error.

**Comment by JohanMabille** [comment]
After diving into the details:
- [inline namespaces](https://json.nlohmann.me/features/namespace/) have been added to nlohmann_json in 3.11.0 to detect this kind of issues at link time (which is exactly what you got here).
- explicitly exposing the *ABI* version in the *API* would turn these link errors into compilation errors when exchanging json objects from different versions. That would not solve the problem, and would prevent xeus-based code to link with libraries and / or applications built with a different version of nlohmann_json, that do not exchange any json object with the xeus code.

I think this problem should be solved by the package manager itself, with "hard-pinning" of the version of nlohman json used to build the different xeus components. Some package managers provide facility to propagate such a pinning (see [run_constrained](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#run-constrained) for conda / mamba for instance).

We can add stricter checks in the CMakeLists.txt files too, to help package managers (or any third party building xeus components) to detect a version mismatch.
